"""new tables

Revision ID: 44e9aa564f93
Revises: 5878d6ef2aff
Create Date: 2025-02-18 16:27:20.551611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e9aa564f93'
down_revision = '5878d6ef2aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_station',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_module',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_station_id', sa.Integer(), nullable=False),
    sa.Column('sensor_module_id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_station_id'], ['base_station.id'], ),
    sa.ForeignKeyConstraint(['sensor_module_id'], ['sensor_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('sensor_module')
    op.drop_table('base_station')
    # ### end Alembic commands ###
