"""add sensor module id

Revision ID: 5878d6ef2aff
Revises: 799f3d35f6c9
Create Date: 2025-02-16 18:33:27.506938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5878d6ef2aff'
down_revision = '799f3d35f6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensormoduleid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_column('sensormoduleid')

    # ### end Alembic commands ###
